services:
  - type: web
    name: real-estate-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn realestate_backend.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
